services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-gradle-allure
    ports:
      - "8080:8080"
      - "50000:50000"
    user: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_config:/var/jenkins_home/init.groovy.d
      - ./tools:/tools
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home:
